name: Sync PPR data
on: push
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Generate PPR data
        run: |
          python3 generator.py -o all
